TestApp/urls.py
from django.contrib import admin
from django.urls import path
from TestApp.views import (
    home,
    login,
    user_dashboard,
    register,
    my_ads,
    my_searches,
    fav_ads,
    settings,
    add_favorite,
    remove_favorite,
    aboutus,
    blog_list,
    blog_detail,
    search_results,
    posts_by_tag_view,
    contact_us,
    faq_view,
    view_pricing_plans,
    buy_plan,
)


app_name = "TestApp"

urlpatterns = [
    path("", home, name="home"),
    path("login", login, name="login"),
    path("dashboard", user_dashboard, name="user_dashboard"),
    path("register", register, name="register"),
    path("my_ads", my_ads, name="my_ads"),
    path("my_searches", my_searches, name="my_searches"),
    path("fav_ads/", fav_ads, name="fav_ads"),
    path("ad/<int:ad_id>/add_favorite/", add_favorite, name="add_favorite"),
    path("ad/<int:ad_id>/remove_favorite/", remove_favorite, name="remove_favorite"),
    path("settings", settings, name="settings"),
    path("aboutus", aboutus, name="aboutus"),
    path("blogs/", blog_list, name="blog_list"),
    path("tags/<int:tag_id>/", posts_by_tag_view, name="posts_by_tag"),
    path("blog/<slug:slug>/", blog_detail, name="blog_detail"),
    path("search", search_results, name="search_results"),
    path("contact", contact_us, name="contact_us"),
    path("faq", faq_view, name="faq"),
    path("price_plan", view_pricing_plans, name="view_pricing_plans"),
    path("buy-plan/<int:plan_id>/", buy_plan, name="buy_plan"),
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static


urlpatterns = [
    path("dj-admin/", admin.site.urls),
    path("tinymce/", include("tinymce.urls")),
    path("", include("TestApp.urls")),
    path("admin/", include("myadmin.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>Home</title>
<!-- Bootstrap stylesheet -->
<link href="{% static '/bootstrap4/css/bootstrap.min.css' %}" rel="stylesheet">
<!-- font -->
<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,900" rel="stylesheet"> 
<!-- stylesheet -->
<link href="{% static '/css/style.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static '/css/style_orange.css' %}" title="style_orange" rel="alternate stylesheet" type="text/css"/>
<link href="{% static '/css/style_blue.css' %}" title="style_blue" rel="alternate stylesheet" type="text/css"/>
<link href="{% static '/css/responsive.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static '/css/ele-style.css' %}" rel="stylesheet" type="text/css"/>
<!-- font-awesome -->
<link href="{% static '/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css" />
<!-- line-awesome -->
<link href="{% static '/line-awesome/css/line-awesome.min.css' %}" rel="stylesheet" type="text/css" />
<!-- crousel css -->
<link href="{% static '/js/owl-carousel/owl.carousel.min.css' %}" rel="stylesheet" type="text/css" />
<!--bootstrap select-->
<link href="{% static '/js/dist/css/bootstrap-select.css' %}" rel="stylesheet" type="text/css" />

</head>
<body>
<!--top start here -->
<div class="top">
	<div class="container">
		<div class="row">
			<div class="col-sm-5 col-xs-12">
				<ul class="list-inline icon">
					<li>
						<!--language code start here-->
						<form  method="post" enctype="multipart/form-data" id="language">
							<div class="btn-group">
								<button class="btn btn-link dropdown-toggle" data-toggle="dropdown">
									<span class="text"><i class="la la-language"></i>English</span> <i class="la la-caret-down"></i>
								</button>
								<ul class="dropdown-menu dropdown-menu-right">
									<li><a href="javascript:;"><img src="static/images/flag.jpg" alt="english" title="english" /> English</a></li>
								</ul>
							</div>
						</form>
						<!--language code end here-->
					</li>
					<li><a href="{% url 'TestApp:login' %}"><i class="la la-plus-square"></i> <span>Login</span></a></li>
					<li><a href="{% url 'TestApp:register' %}"><i class="la la-key"></i> <span>Register</span></a></li> 
				</ul>
			</div>
			<div class="col-md-7 col-sm-7 col-xs-12">
				<div class="topnav responsive" id="myTopnav">
					<ul class="list-inline">
						<li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Home</a>
							<div class="dropdown-menu">
								<div class="dropdown-inner">
									<ul class="list-unstyled">
										<li><a href="{% url "TestApp:home" %}">Homepage</a></li>
									</ul>
								</div>
							</div>
						</li>
						<li><a href="{% url "TestApp:aboutus" %}">About</a></li>
						<li class="dropdown" ><a data-toggle="dropdown" href="#">Blog</a>
							<div class="dropdown-menu">
								<div class="dropdown-inner">
									<ul class="list-unstyled">
										<li><a href="{% url "TestApp:blog_list" %}">Our Blog</a></li>
										{% comment %} <li><a href="{% url "TestApp:blog_detail" id %}">Blog Detail</a></li> {% endcomment %}
									</ul>
								</div>
							</div>
						</li>
						<li><a href="{% url "TestApp:contact_us" %}">Contact</a></li>
						<li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Pages</a>
							<div class="dropdown-menu">
								<div class="dropdown-inner">
									<ul class="list-unstyled">
										<li><a href="{% url "TestApp:faq" %}">FAQ</a></li>
										{% comment %} <li><a href="dashboard.html">Dashboard</a></li> {% endcomment %}
										<li><a href="{% url "TestApp:view_pricing_plans" %}">Pricing Plans</a></li>
										<li><a href="all_ads.html"> All Ads</a></li>
										<li><a href="ads_single_view.html">Ads Single View</a></li>
									</ul>
								</div>
							</div>
						</li>
						<li><a href="terms_and_conditions.html">Term & Conditions</a></li>
						<li><a href="javascript:void(0);" class="icons" onclick="myFunction()">&#9776;</a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
<!--top end here -->

<!-- header start here-->
<header>
	<div class="container">
		<div class="row">
			<div class="col-md-3 col-sm-3 col-xs-12">
				<div id="logo">
					<a href="index.html"><img class="img-fluid logochange" src="{% static '/images/logo.png' %}" alt="logo" title="logo" /></a>
				</div>
			</div>
				
			<div class="col-md-7 col-sm-7 col-xs-12">
				<form class="form-horizontal category" method="post">
					<div class="row">
						<div class="col-sm-3 paddright">
							<div class="form-group">
								<select class="selectpicker form-control bs-select-hidden" name="location">
									<option value="1">Select City</option>
									<option value="0">Ludhiana</option>
									<option value="0">Jalandhar</option>
									<option value="0">Moga</option>
									<option value="0">Ambala</option>
									<option value="0">Amritsar</option>
									<option value="0">Delhi</option>
								</select>
							</div>
						</div>
						<div class="col-sm-3 paddright">
							<div class="form-group">
								<select class="selectpicker form-control bs-select-hidden" name="location">
									<option value="1">Select Category</option>
									<option value="0">Vehicle</option>
									<option value="0">Mobiles</option>
									<option value="0">Electonics</option>
									<option value="0">Real Estate</option>
									<option value="0">Fashion</option>
									<option value="0">Furniture</option>
									<option value="0">Jobs</option>
									<option value="0">Services</option>
									<option value="0">Pets</option>
									<option value="0">Education</option>
									<option value="0">Matrimony</option>
									<option value="0">Note and Coins</option>
								</select>
							</div>
						</div>
						<div class="col-sm-6 search">
							<div class="form-group">
								<input name="s" value="" class="form-control" placeholder="Enter Keyword" type="text">
								<button type="submit" value="submit" class="btn"><i class="icon_search" aria-hidden="true"></i></button>
							</div>
						</div>
                    </div>
				</form>
			</div>
			<div class="col-md-2 col-sm-2 col-xs-12 center">
				<button class="btn-primary btn-block" type="button" onclick="location.href='add_listing.html'"> <i class="la la-edit"></i>Add listing</button>
			</div>
		</div>
	</div>
</header>
<!-- header end here -->
{% block content %}
{% endblock %} 

<!-- footer start here -->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-sm-4 col-xs-12 matter">
                <img src="{% static '/images/logo.png' %}" class="img-fluid logochange" alt="logo" title="logo" />
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc est justo, aliquam nec tempor fermentum, commodo et libero. Quisque et rutrum arcu. Vivamus dictum tincidunt magna id euismod. Nam sollicitudin mi quis orci lobortis feugiat.</p>
				
            </div>
            <div class="col-md-3 col-sm-3 col-xs-12 info">
                <h5>Useful Links</h5>
				<ul class="list-inline links">
                    <li><a href="{% url "TestApp:home" %}">Home</a></li>
					<li><a href="{% url "TestApp:view_pricing_plans" %}">Pricing Plans</a></li>
                    <li><a href="{% url "TestApp:aboutus" %}">About</a></li>
					<li><a href="{% url "TestApp:faq" %}">FAQ</a></li>
                    <li><a href="{% url "TestApp:blog_list" %}">Blog</a></li>
					<li><a href="all_ads.html">All Ads</a></li>
                    <li><a href="{% url "TestApp:login" %}">Login</a></li>
					<li><a href="{% url "TestApp:contact_us" %}">Help & Contact us</a></li>
                    <li><a href="{% url "TestApp:register" %}">Register</a></li>
                    <li><a href="terms_and_conditions.html">Terms & Conditions</a></li>
                </ul>
            </div>
            <div class="col-md-4 col-sm-4 col-xs-12">
                <h5>Contact with us</h5>
				<ul class="list-inline social">
                    <li><a href="https://www.facebook.com/" target="_blank"><i class="fa fa-facebook"></i></a></li>
                    <li><a href="https://twitter.com/" target="_blank"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                    <li><a href="https://plus.google.com/" target="_blank"><i class="social_googleplus" aria-hidden="true"></i></a></li>
                    <li><a href="https://www.instagram.com/" target="_blank"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
					<li><a href="https://www.youtube.com/" target="_blank"><i class="social_youtube"></i></a></li>
                    <li><a href="https://in.linkedin.com/" target="_blank"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
                </ul>
            </div>
        </div>
    </div>
	<div class="powered">
		<div class="container">
			<div class="row">
				<div class="col-sm-12 col-xs-12 text-center">
					<p>© 2024 <span>Suvam</span>. All rights reserved. Maintained by <span>Suvam</span></p>
				</div>
			</div>
		</div>
	</div>
</footer>
<!-- footer end here -->
		
<!-- jquery -->
<script src="{% static '/js/jquery-3.2.1.min.js' %}" type="text/javascript"></script>
<!-- bootstrap js -->
<script src="{% static '/js/popper.min.js' %}" type="text/javascript"></script>
<script src="{% static '/bootstrap4/js/bootstrap.min.js' %}" type="text/javascript"></script>
<!--bootstrap select-->
<script src="{% static '/js/dist/js/bootstrap-select.js' %}"></script>
<!-- owlcarousel js -->
<script src="{% static '/js/holder.min.js' %}" type="text/javascript"></script>
<script src="{% static '/js/owl-carousel/owl.carousel.min.js' %}" type="text/javascript"></script>
<!--internal js-->
<script src="{% static '/js/owlinternal.js' %}"></script>
<script src="{% static '/js/internal.js' %}"></script>
<script src="{% static '/js/switcher.js' %}"></script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-115890069-6"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-115890069-6');
</script>

</body>
</html>

templates/dashboard_fav_ads.html
{% extends "base.html" %}
{% load static %}
{% load custom_filters %}  <!-- Ensure your custom filters are loaded -->

{% block content %}
<div class="topimage">
    <img src="{% static 'images/bck_bg.jpg' %}" class="img-fluid" alt="Background image" title="Background image"> <!-- Use static tag -->
</div>

<!-- ad-single start here -->
<div class="commontop">
    <div class="container"> 
        <div class="row">
            <div class="col-sm-12 col-xs-12">
                <div class="dashboard">
                    <div class="profile">
                        <div class="col-sm-3 col-xs-12">
                            <img class="img-fluid" src="{% static 'images/dashboard/dp.png' %}" alt="Profile image" title="Profile image"> <!-- Use static tag -->
                        </div>
                        <div class="col-sm-9 col-xs-12 padd0">
                            <h4>{{ user.get_full_name|default:user.username }}</h4>  <!-- Dynamic user name -->
                            <div class="common">
                                <p class="des"><i class="la la-map-marker"></i> {{ user.profile.location|default:"Location not available" }}</p>  <!-- Assuming you have a user profile with location -->
                                <p class="des1">Create Account: {{ user.date_joined|date:"Y-m-d" }}</p>  <!-- Show account creation time -->
                            </div>
                            <ul class="list-inline">
                                <li><a href="{% url 'TestApp:user_dashboard' %}"><img src="{% static 'images/dashboard/grid.png' %}" alt="Dashboard" title="Dashboard" /><p>Dashboard</p></a></li>
                                <li><a href="{% url 'TestApp:my_ads' %}"><img src="{% static 'images/dashboard/card.png' %}" alt="My Ads" title="My Ads" /><p>My Ads</p></a></li>
                                <li><a href="{% url 'TestApp:my_searches' %}"><img src="{% static 'images/dashboard/search.png' %}" alt="My Searches" title="My Searches" /><p>My Searches</p></a></li>
                                <li class="active"><a href="{% url 'TestApp:fav_ads' %}"><img src="{% static 'images/dashboard/heart.png' %}" alt="Favourite Ads" title="Favourite Ads" /><p>Favourite Ads</p></a></li>
                                <li><a href="{% url 'TestApp:settings' %}"><img src="{% static 'images/dashboard/setting.png' %}" alt="Settings" title="Settings" /><p>Setting</p></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="inner-fav">
                        {% if ads %}
                            {% for ad in ads %}
                                <div class="product-layout product-list">
                                    <div class="product-thumb">
                                        <div class="image">
                                            <a href="{% url 'ad_detail' ad.id %}"><img src="{{ ad.image.url }}" alt="{{ ad.title }}" title="{{ ad.title }}" class="img-fluid"></a>
                                        </div>
                                        <div class="caption">
                                            <h4><a href="{% url 'ad_detail' ad.id %}">{{ ad.title }}</a></h4>
                                            <p class="des">Category: {{ ad.category }}</p>
                                            <ul class="list-unstyled">
                                                <li><i class="la la-map-marker"></i> {{ ad.location }}</li>
                                                <li><i class="la la-clock-o"></i> {{ ad.created_at|timeago_format }}</li>  <!-- Use the custom filter -->
                                            </ul>
                                            <hr>
                                            <p class="des">{{ ad.description }}</p>
                                            <div class="button-group text-center visible-xs">
                                                <button type="button">${{ ad.price }}</button>
                                                <button type="button"><i class="la la-envelope-o"></i></button>
                                                <button type="button"><i class="la la-phone"></i></button>
                                                <button type="button"><i class="la la-heart-o"></i></button>
                                            </div>
                                        </div>
                                        <div class="button-group text-center hidden-xs">
                                            <button type="button">${{ ad.price }}</button>
                                            <button type="button"><i class="la la-envelope-o"></i></button>
                                            <button type="button"><i class="la la-phone"></i></button>
                                            <button type="button"><i class="la la-heart-o"></i></button>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        {% else %}
                            <p>No favorite ads found.</p>  <!-- Message when no ads are found -->
                        {% endif %}
                        <div class="text-center icon">
                            <i class="la la-spinner fa-spin"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- ad-single end here -->
{% endblock %}


{% comment %} {% extends "base.html" %}
{% load static %}
{% block content %}
<div class="topimage">
	<img src="images/bck_bg.jpg" class="img-fluid" alt="image" title="image">
</div>

<!-- ad-single start here -->
<div class="commontop">
	<div class="container"> 
		<div class="row">
			<div class="col-sm-12 col-xs-12">
				<div class="dashboard">
					<div class="profile">
						<div class="col-sm-3 col-xs-12">
							<img class="img-fluid" src="images/dashboard/dp.png" alt="image" title="image">
						</div>
						<div class="col-sm-9 col-xs-12 padd0">
							<h4>John Doe</h4>
							<div class="common">
								<p class="des"><i class="la la-map-marker"></i> Ludhiana, Punjab</p>
								<p class="des1">Create Account : 2 Years ago</p>
							</div>
							<ul class="list-inline">
								<li ><a href="dashboard.html"><img src="images/dashboard/grid.png" alt="image" title="image" /><p>Dashboard</p></a></li>
								<li ><a href="dashboard_my_ads.html"><img src="images/dashboard/card.png" alt="image" title="image" /><p>My Ads</p></a></li>
								<li><a href="dashboard_my_searches.html"><img src="images/dashboard/search.png" alt="image" title="image" /><p>My Searches</p></a></li>
								<li class="active"><a href="dashboard_fav_ads.html"><img src="images/dashboard/heart.png" alt="image" title="image" /><p>Favourite Ads</p></a></li>
								<li><a href="dashboard_message.html"><img src="images/dashboard/message.png" alt="image" title="image" /><p>Messages</p></a></li>
								<li><a href="dashboard_setting.html"><img src="images/dashboard/setting.png" alt="image" title="image" /><p>Setting</p></a></li>
							</ul>
						</div>
					</div>
					<div class="inner-fav">
						<div class="product-layout product-list">
							<div class="product-thumb">
								<div class="image">
									<a href="ads_single_view.html"><img src="images/mobile/01.jpg" alt="image" title="image" class="img-fluid"></a>
								</div>
								<div class="caption">
									<h4><a href="ads_single_view.html">Ads post title here</a></h4>
									<p class="des">Category : Vehicle</p>
									<ul class="list-unstyled">
										<li><i class="la la-map-marker"></i> Ludhiana, Punjab, India</li>
										<li><i class="la la-clock-o"></i> 15 Hour ago</li>
									</ul>
									<hr>
									<p class="des">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam pretium dictum diam vel laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer dictum justo nec lacus porta congue....</p>
									<div class="button-group text-center visible-xs">
										<button type="button">$ 12000</button>
										<button type="button"><i class="la la-envelope-o"></i></button>
										<button type="button"><i class="la la-phone"></i></button>
										<button type="button"><i class="la la-heart-o"></i></button>
									</div>
								</div>
								<div class="button-group text-center hidden-xs">
									<button type="button">$ 12000</button>
									<button type="button"><i class="la la-envelope-o"></i></button>
									<button type="button"><i class="la la-phone"></i></button>
									<button type="button"><i class="la la-heart-o"></i></button>
								</div>
							</div>
						</div>
						<div class="product-layout product-list">
							<div class="product-thumb">
								<div class="image">
									<a href="ads_single_view.html"><img src="images/mobile/01.jpg" alt="image" title="image" class="img-fluid"></a>
								</div>
								<div class="caption">
									<h4><a href="ads_single_view.html">Ads post title here</a></h4>
									<p class="des">Category : Vehicle</p>
									<ul class="list-unstyled">
										<li><i class="la la-map-marker"></i> Ludhiana, Punjab, India</li>
										<li><i class="la la-clock-o"></i> 15 Hour ago</li>
									</ul>
									<hr>
									<p class="des">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam pretium dictum diam vel laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer dictum justo nec lacus porta congue....</p>
									<div class="button-group text-center visible-xs">
										<button type="button">$ 12000</button>
										<button type="button"><i class="la la-envelope-o"></i></button>
										<button type="button"><i class="la la-phone"></i></button>
										<button type="button"><i class="la la-heart-o"></i></button>
									</div>
								</div>
								<div class="button-group text-center hidden-xs">
									<button type="button">$ 12000</button>
									<button type="button"><i class="la la-envelope-o"></i></button>
									<button type="button"><i class="la la-phone"></i></button>
									<button type="button"><i class="la la-heart-o"></i></button>
								</div>
							</div>
						</div>
						<div class="product-layout product-list">
							<div class="product-thumb">
								<div class="image">
									<a href="ads_single_view.html"><img src="images/mobile/01.jpg" alt="image" title="image" class="img-fluid"></a>
								</div>
								<div class="caption">
									<h4><a href="ads_single_view.html">Ads post title here</a></h4>
									<p class="des">Category : Vehicle</p>
									<ul class="list-unstyled">
										<li><i class="la la-map-marker"></i> Ludhiana, Punjab, India</li>
										<li><i class="la la-clock-o"></i> 15 Hour ago</li>
									</ul>
									<hr>
									<p class="des">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam pretium dictum diam vel laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer dictum justo nec lacus porta congue....</p>
									<div class="button-group text-center visible-xs">
										<button type="button">$ 12000</button>
										<button type="button"><i class="la la-envelope-o"></i></button>
										<button type="button"><i class="la la-phone"></i></button>
										<button type="button"><i class="la la-heart-o"></i></button>
									</div>
								</div>
								<div class="button-group text-center hidden-xs">
									<button type="button">$ 12000</button>
									<button type="button"><i class="la la-envelope-o"></i></button>
									<button type="button"><i class="la la-phone"></i></button>
									<button type="button"><i class="la la-heart-o"></i></button>
								</div>
							</div>
						</div>
						<div class="product-layout product-list">
							<div class="product-thumb">
								<div class="image">
									<a href="ads_single_view.html"><img src="images/mobile/01.jpg" alt="image" title="image" class="img-fluid"></a>
								</div>
								<div class="caption">
									<h4><a href="ads_single_view.html">Ads post title here</a></h4>
									<p class="des">Category : Vehicle</p>
									<ul class="list-unstyled">
										<li><i class="la la-map-marker"></i> Ludhiana, Punjab, India</li>
										<li><i class="la la-clock-o"></i> 15 Hour ago</li>
									</ul>
									<hr>
									<p class="des">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam pretium dictum diam vel laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer dictum justo nec lacus porta congue....</p>
									<div class="button-group text-center visible-xs">
										<button type="button">$ 12000</button>
										<button type="button"><i class="la la-envelope-o"></i></button>
										<button type="button"><i class="la la-phone"></i></button>
										<button type="button"><i class="la la-heart-o"></i></button>
									</div>
								</div>
								<div class="button-group text-center hidden-xs">
									<button type="button">$ 12000</button>
									<button type="button"><i class="la la-envelope-o"></i></button>
									<button type="button"><i class="la la-phone"></i></button>
									<button type="button"><i class="la la-heart-o"></i></button>
								</div>
							</div>
						</div>
						<div class="text-center icon">
							<i class="la la-spinner fa-spin"></i>
						</div>
					</div>
					
				</div>
			</div>
		</div>
	</div>
</div>
<!-- ad-single end here -->
{% endblock %} {% endcomment %}

templates/faq.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<!-- breadcrumb end here -->
<div class="topimage">
	<img src="{% static 'images/bck_bg.jpg' %}" class="img-fluid" alt="image" title="image" />
</div>
<div class="bread-crumb">
	<div class="container">
		<div class="matter">
			<div class="pull-left">
				<ul class="list-inline">
					<li><a href="{% url "TestApp:home" %}">Home</a></li>
					<li><a href="{% url "TestApp:faq" %}">FAQ</a></li>
				</ul>
			</div>
			<div class="pull-right">
				<h2>FAQ</h2>
			</div>
		</div>
	</div>
</div>
<!-- breadcrumb end here -->

<!-- faq start here -->
<div class="commontop">
    <div class="container"> 
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="faq">
                    <h5>FAQ</h5>
                    <hr />
                    <div class="panel-group" id="accordion">
                        {% for faq in faqs %}
                        <div class="panel panel-default {% if forloop.first %}active{% endif %}">
                            <div class="panel-heading">
                                <a data-toggle="collapse" href="#collapse{{ forloop.counter }}" role="button" aria-expanded="{% if forloop.first %}true{% else %}false{% endif %}" aria-controls="collapse{{ forloop.counter }}">
                                    <h4 class="panel-title">{{ faq.question }} <i class="fa fa-angle-right" aria-hidden="true"></i></h4>
                                </a>
                            </div>
                            <div id="collapse{{ forloop.counter }}" class="panel-collapse collapse {% if forloop.first %}show{% endif %}" aria-labelledby="heading{{ forloop.counter }}" data-parent="#accordion">
                                <div class="panel-body">
                                    <p>{{ faq.answer|safe }}</p>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>  
                </div>
            </div>
        </div>
    </div>
</div>
<!-- faq end here -->

{% endblock %}

templates/price_plan.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<!-- breadcrumb end here -->
<div class="topimage">
	<img src="{% static 'images/bck_bg.jpg' %}" class="img-fluid" alt="image" title="image" />
</div>
<div class="bread-crumb">
	<div class="container">
		<div class="matter">
			<div class="pull-left">
				<ul class="list-inline">
					<li><a href="{% url "TestApp:home" %}">Home</a></li>
					<li><a href="{% url "TestApp:view_pricing_plans" %}">Pricing Plans</a></li>
				</ul>
			</div>
			<div class="pull-right">
				<h2>Pricing Plans</h2>
			</div>
		</div>
	</div>
</div>
<!-- breadcrumb end here -->


<!-- pricing start here -->
<div class="commontop ">
    <div class="container"> 
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12 priceplan">
                <h5>Pricing Plans</h5>
                <hr />
                <ul class="list-inline">
                    {% for plan in plans %}
                    <li>
                        <div class="heading"><p>{{ forloop.counter }}</p><span>{{ plan.title }}</span></div>
                        <div class="matter">
                            <div class="special">${{ plan.price }}</div>
                            <p>{{ plan.duration_days }} D</p>
                            <span>{{ plan.description|safe }}</span>
                        </div>
                        <p class="text"><i class="la la-check"></i> {% if plan.ad_posting %} Free Ad Posting {% else %} No Free Ad Posting {% endif %}</p>
                        <p class="text"><i class="la la-check"></i> {% if plan.features_ad_availability %} Feature Ad Availability {% else %} No Feature Ad Availability {% endif %}</p>
                        <p class="text"><i class="la la-check"></i> For {{ plan.duration_days }} Days</p>
                        <p class="text bor"><i class="la la-check"></i> {% if plan.security_guarantee %} 100% Secure {% else %} Not Secure {% endif %}</p>
                        <div class="text-center">
                            <button type="button">Buy Now</button>
                        </div>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>

{% endblock %}